name:                scraper
version:             0.1.0.0
github:              "githubuser/DoughboysWikiScraper"
license:             BSD3
author:              "Daniel Tuveson"
maintainer:          "danieltuveson@gmail.com"
copyright:           "2021 Daniel Tuveson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/danieltuveson/DoughboysWikiScraper#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- wreq
- containers
- aeson
- lens-aeson
- pretty-simple
- HTTP
- attoparsec
- text
- bytestring
- mtl
- vector
- safe
- uri-encode

library:
  source-dirs: src
  ghc-options:
    - -XOverloadedStrings

executables:
  scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XOverloadedStrings
    - -Wall
    - -Wno-name-shadowing
    dependencies:
    - scraper

tests:
  scraper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XOverloadedStrings
    dependencies:
    - scraper
    - hspec
